spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SteamAnalyst
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    generate-unique-name: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 4001

jwt:
  secret : VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
